// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Discount Codes → Code*
 */
export interface DiscountCodesDocumentDataCodeItem {
  /**
   * Code field in *Discount Codes → Code*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: discount_codes.code[].code
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  code: prismic.KeyTextField;

  /**
   * Percentage Off field in *Discount Codes → Code*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: discount_codes.code[].percentage_off
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  percentage_off: prismic.NumberField;

  /**
   * Start Date field in *Discount Codes → Code*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: discount_codes.code[].start_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  start_date: prismic.DateField;

  /**
   * Expiry Date field in *Discount Codes → Code*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: discount_codes.code[].expiry_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  expiry_date: prismic.DateField;

  /**
   * Active field in *Discount Codes → Code*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: discount_codes.code[].active
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  active: prismic.BooleanField;
}

/**
 * Content for Discount Codes documents
 */
interface DiscountCodesDocumentData {
  /**
   * Code field in *Discount Codes*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: discount_codes.code[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  code: prismic.GroupField<Simplify<DiscountCodesDocumentDataCodeItem>>;
}

/**
 * Discount Codes document from Prismic
 *
 * - **API ID**: `discount_codes`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DiscountCodesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DiscountCodesDocumentData>,
    "discount_codes",
    Lang
  >;

/**
 * Item in *Menu → Column*
 */
export interface MenuDocumentDataColumnItem {
  /**
   * Title field in *Menu → Column*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.column[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *Menu → Column*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.column[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Logo field in *Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.logo
   * - **Tab**: Top menu
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Link field in *Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.top_menu_link
   * - **Tab**: Top menu
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  top_menu_link: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Standard" | "Special" | "Basket"
    >
  >; /**
   * Link field in *Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.bottom_menu_link
   * - **Tab**: Bottom menu
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  bottom_menu_link: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Standard" | "Highlighted"
    >
  >; /**
   * Column field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.column[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  column: prismic.GroupField<Simplify<MenuDocumentDataColumnItem>>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type PageDocumentDataSlicesSlice =
  | TwoColumnsSlice
  | BlogPostsSlice
  | TextSlice
  | ImageSlice
  | HeroSlice
  | CarouselSlice
  | FaqSlice
  | CheckoutFormSlice
  | BasketSlice
  | ContactFormSlice
  | GallerySlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>; /**
   * Background Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.background_image
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Colour field in *Page*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.background_colour
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_colour: prismic.ColorField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Blog post → Types*
 */
export interface PostDocumentDataTypesItem {
  /**
   * Type field in *Blog post → Types*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: post.types[].type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<"Inspiration" | "How to" | "Science">;
}

type PostDocumentDataSlicesSlice =
  | VideoSlice
  | ContactFormSlice
  | TwoColumnsSlice
  | FaqSlice
  | GallerySlice
  | CarouselSlice
  | TextSlice
  | HeroSlice
  | ImageSlice;

/**
 * Content for Blog post documents
 */
interface PostDocumentData {
  /**
   * Title field in *Blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Excerpt field in *Blog post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField;

  /**
   * Date field in *Blog post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: post.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Types field in *Blog post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: post.types[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  types: prismic.GroupField<Simplify<PostDocumentDataTypesItem>>;

  /**
   * Image field in *Blog post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Blog post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PostDocumentDataSlicesSlice>; /**
   * Meta title field in *Blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta description field in *Blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta image field in *Blog post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PostDocumentData>, "post", Lang>;

/**
 * Item in *Product → Variations*
 */
export interface ProductDocumentDataVariationsItem {
  /**
   * Label field in *Product → Variations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.variations[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Description field in *Product → Variations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.variations[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Variation field in *Product → Variations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.variations[].variation
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  variation: prismic.KeyTextField;

  /**
   * Price field in *Product → Variations*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product.variations[].price
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  price: prismic.NumberField;
}

/**
 * Item in *Product → Linked products*
 */
export interface ProductDocumentDataLinkedProductsItem {
  /**
   * Product field in *Product → Linked products*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product.linked_products[].product
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  product: ContentRelationshipFieldWithData<
    [
      {
        id: "product";
        fields: [
          "title",
          "description",
          { id: "gallery"; fields: ["image"] },
          "price",
          "active",
          {
            id: "category";
            customtypes: [{ id: "product_category"; fields: ["name"] }];
          },
        ];
      },
    ]
  >;
}

type ProductDocumentDataSlicesSlice =
  | VideoSlice
  | TextSlice
  | TwoColumnsSlice
  | ImageSlice
  | HeroSlice
  | GallerySlice
  | ContactFormSlice
  | FaqSlice
  | CarouselSlice;

/**
 * Item in *Product → Gallery*
 */
export interface ProductDocumentDataGalleryItem {
  /**
   * Image field in *Product → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.gallery[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Product → Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.gallery[].caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;

  /**
   * Description field in *Product → Gallery*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.gallery[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * SKU field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.sku
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sku: prismic.KeyTextField;

  /**
   * Category field in *Product*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  category: prismic.ContentRelationshipField<"product_category">;

  /**
   * Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * MOQ field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.moq
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  moq: prismic.KeyTextField;

  /**
   * Active field in *Product*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: product.active
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  active: prismic.BooleanField;

  /**
   * Price field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  price: prismic.NumberField;

  /**
   * Variations field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.variations[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  variations: prismic.GroupField<Simplify<ProductDocumentDataVariationsItem>>;

  /**
   * Linked products field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.linked_products[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  linked_products: prismic.GroupField<
    Simplify<ProductDocumentDataLinkedProductsItem>
  >;

  /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProductDocumentDataSlicesSlice>; /**
   * Gallery field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.gallery[]
   * - **Tab**: Gallery
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery: prismic.GroupField<Simplify<ProductDocumentDataGalleryItem>>; /**
   * Meta Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

type ProductCategoryDocumentDataSlicesSlice =
  | VideoSlice
  | TwoColumnsSlice
  | HeroSlice
  | ImageSlice
  | TextSlice
  | GallerySlice
  | ContactFormSlice
  | CarouselSlice
  | FaqSlice;

/**
 * Content for Product Category documents
 */
interface ProductCategoryDocumentData {
  /**
   * Plural URL field in *Product Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.plural_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  plural_url: prismic.KeyTextField;

  /**
   * Name field in *Product Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Price field in *Product Category*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  price: prismic.NumberField;

  /**
   * Postage Price - UK field in *Product Category*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.postage_price_uk
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  postage_price_uk: prismic.NumberField;

  /**
   * Postage Price - Europe field in *Product Category*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.postage_price_eu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  postage_price_eu: prismic.NumberField;

  /**
   * Postage Price - North America field in *Product Category*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.postage_price_na
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  postage_price_na: prismic.NumberField;

  /**
   * Postage Price - South America field in *Product Category*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.postage_price_sa
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  postage_price_sa: prismic.NumberField;

  /**
   * Postage Price - Africa field in *Product Category*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.postage_price_af
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  postage_price_af: prismic.NumberField;

  /**
   * Postage Price - Asia field in *Product Category*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.postage_price_as
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  postage_price_as: prismic.NumberField;

  /**
   * Postage Price - Oceania field in *Product Category*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.postage_price_oc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  postage_price_oc: prismic.NumberField;

  /**
   * Postage Price - Other field in *Product Category*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.postage_price_other
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  postage_price_other: prismic.NumberField;

  /**
   * Slice Zone field in *Product Category*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProductCategoryDocumentDataSlicesSlice>; /**
   * Meta Title field in *Product Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product_category.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Product Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product_category.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Product Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>; /**
   * Background Image field in *Product Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.background_image
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Colour field in *Product Category*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: product_category.background_colour
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_colour: prismic.ColorField;
}

/**
 * Product Category document from Prismic
 *
 * - **API ID**: `product_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductCategoryDocumentData>,
    "product_category",
    Lang
  >;

export type AllDocumentTypes =
  | DiscountCodesDocument
  | MenuDocument
  | PageDocument
  | PostDocument
  | ProductDocument
  | ProductCategoryDocument;

/**
 * Primary content in *Basket → Default → Primary*
 */
export interface BasketSliceDefaultPrimary {
  /**
   * Empty Basket Message field in *Basket → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: basket.default.primary.empty_basket_message
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  empty_basket_message: prismic.RichTextField;
}

/**
 * Default variation for Basket Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BasketSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BasketSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Basket*
 */
type BasketSliceVariation = BasketSliceDefault;

/**
 * Basket Shared Slice
 *
 * - **API ID**: `basket`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BasketSlice = prismic.SharedSlice<"basket", BasketSliceVariation>;

/**
 * Primary content in *BlogPosts → Default → Primary*
 */
export interface BlogPostsSliceDefaultPrimary {
  /**
   * Homepage field in *BlogPosts → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_posts.default.primary.homepage
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  homepage: prismic.BooleanField;
}

/**
 * Default variation for BlogPosts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogPostsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPosts*
 */
type BlogPostsSliceVariation = BlogPostsSliceDefault;

/**
 * BlogPosts Shared Slice
 *
 * - **API ID**: `blog_posts`
 * - **Description**: BlogPosts
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogPostsSlice = prismic.SharedSlice<
  "blog_posts",
  BlogPostsSliceVariation
>;

/**
 * Item in *Carousel → Default → Primary → Slide*
 */
export interface CarouselSliceDefaultPrimarySlideItem {
  /**
   * Image field in *Carousel → Default → Primary → Slide*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.slide[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Carousel → Default → Primary → Slide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.slide[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Carousel → Default → Primary → Slide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.slide[].subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Link field in *Carousel → Default → Primary → Slide*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.slide[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Carousel → Default → Primary*
 */
export interface CarouselSliceDefaultPrimary {
  /**
   * Initial slide field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.initial_slide
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  initial_slide: prismic.NumberField;

  /**
   * Autoplay field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: carousel.default.primary.autoplay
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  autoplay: prismic.BooleanField;

  /**
   * Bottom margin field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: carousel.default.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Slide field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.slide[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  slide: prismic.GroupField<Simplify<CarouselSliceDefaultPrimarySlideItem>>;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Primary content in *Checkout Form → Default → Primary*
 */
export interface CheckoutFormSliceDefaultPrimary {
  /**
   * Empty Basket Message field in *Checkout Form → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: checkout_form.default.primary.empty_basket_message
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  empty_basket_message: prismic.RichTextField;

  /**
   * Error Message field in *Checkout Form → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: checkout_form.default.primary.error_message
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  error_message: prismic.RichTextField;

  /**
   * Confirmation Message field in *Checkout Form → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: checkout_form.default.primary.confirmation_message
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  confirmation_message: prismic.RichTextField;
}

/**
 * Default variation for Checkout Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CheckoutFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CheckoutFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Checkout Form*
 */
type CheckoutFormSliceVariation = CheckoutFormSliceDefault;

/**
 * Checkout Form Shared Slice
 *
 * - **API ID**: `checkout_form`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CheckoutFormSlice = prismic.SharedSlice<
  "checkout_form",
  CheckoutFormSliceVariation
>;

/**
 * Primary content in *Contact Form → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Confirmation Message field in *Contact Form → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.confirmation_message
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  confirmation_message: prismic.RichTextField;

  /**
   * Error Message field in *Contact Form → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.error_message
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  error_message: prismic.RichTextField;
}

/**
 * Default variation for Contact Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact Form*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * Contact Form Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *FAQ → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Content field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Background Image field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Colour field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_colour: prismic.ColorField;

  /**
   * Background Size field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Contain
   * - **API ID Path**: faq.default.primary.background_size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_size: prismic.SelectField<"Contain" | "Cover", "filled">;

  /**
   * Alignment field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: faq.default.primary.alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  alignment: prismic.SelectField<"Left" | "Center" | "Right", "filled">;

  /**
   * Top Padding field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: faq.default.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Bottom Padding field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: faq.default.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Primary content in *FAQ → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * Question field in *FAQ → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FAQ → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for FAQ Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *FAQ*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * FAQ Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Gallery → Default → Primary*
 */
export interface GallerySliceDefaultPrimary {
  /**
   * Content field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Background Colour field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_colour: prismic.ColorField;

  /**
   * Alignment field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: gallery.default.primary.alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  alignment: prismic.SelectField<"Left" | "Center" | "Right", "filled">;

  /**
   * Columns field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: gallery.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  columns: prismic.SelectField<"1" | "2" | "3" | "4", "filled">;

  /**
   * Top Padding field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: gallery.default.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Bottom Padding field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: gallery.default.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Product listing field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: gallery.default.primary.product_listing
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  product_listing: prismic.BooleanField;
}

/**
 * Primary content in *Gallery → Items*
 */
export interface GallerySliceDefaultItem {
  /**
   * Image field in *Gallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *Gallery → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Title field in *Gallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Caption field in *Gallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;

  /**
   * Product field in *Gallery → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].product
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  product: prismic.ContentRelationshipField<"product">;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySliceDefaultPrimary>,
  Simplify<GallerySliceDefaultItem>
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySlice = prismic.SharedSlice<
  "gallery",
  GallerySliceVariation
>;

/**
 * Primary content in *Hero → Standard → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Standard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *Hero → Standard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Image field in *Hero → Standard → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Background color field in *Hero → Standard → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;

  /**
   * Background image field in *Hero → Standard → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Bottom margin field in *Hero → Standard → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: hero.default.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Standard variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Image → Full width image → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Full width image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * URL field in *Image → Full width image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Bottom margin field in *Image → Full width image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: image.default.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Full width image variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Image → Content width image → Primary*
 */
export interface ImageSliceContentWidthImagePrimary {
  /**
   * Image field in *Image → Content width image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.contentWidthImage.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * URL field in *Image → Content width image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image.contentWidthImage.primary.url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Bottom margin field in *Image → Content width image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: image.contentWidthImage.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Content width image variation for Image Slice
 *
 * - **API ID**: `contentWidthImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceContentWidthImage = prismic.SharedSliceVariation<
  "contentWidthImage",
  Simplify<ImageSliceContentWidthImagePrimary>,
  never
>;

/**
 * Primary content in *Image → Wide image → Primary*
 */
export interface ImageSliceWideImagePrimary {
  /**
   * Image field in *Image → Wide image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.wideImage.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * URL field in *Image → Wide image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image.wideImage.primary.url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Bottom margin field in *Image → Wide image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: image.wideImage.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Wide image variation for Image Slice
 *
 * - **API ID**: `wideImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceWideImage = prismic.SharedSliceVariation<
  "wideImage",
  Simplify<ImageSliceWideImagePrimary>,
  never
>;

/**
 * Primary content in *Image → Browser width image → Primary*
 */
export interface ImageSliceBrowserWidthImagePrimary {
  /**
   * Image field in *Image → Browser width image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.browserWidthImage.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * URL field in *Image → Browser width image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image.browserWidthImage.primary.url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Bottom margin field in *Image → Browser width image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: image.browserWidthImage.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Browser width image variation for Image Slice
 *
 * - **API ID**: `browserWidthImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceBrowserWidthImage = prismic.SharedSliceVariation<
  "browserWidthImage",
  Simplify<ImageSliceBrowserWidthImagePrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation =
  | ImageSliceDefault
  | ImageSliceContentWidthImage
  | ImageSliceWideImage
  | ImageSliceBrowserWidthImage;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *Text → Full width text → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Text field in *Text → Full width text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Alignment field in *Text → Full width text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: text.default.primary.alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  alignment: prismic.SelectField<"Left" | "Center" | "Right", "filled">;

  /**
   * Bottom margin field in *Text → Full width text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: text.default.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Full width text variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Text → Content width text → Primary*
 */
export interface TextSliceContentWidthTextPrimary {
  /**
   * Text field in *Text → Content width text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.contentWidthText.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Alignment field in *Text → Content width text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: text.contentWidthText.primary.alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  alignment: prismic.SelectField<"Left" | "Center" | "Right", "filled">;

  /**
   * Bottom margin field in *Text → Content width text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: text.contentWidthText.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Content width text variation for Text Slice
 *
 * - **API ID**: `contentWidthText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceContentWidthText = prismic.SharedSliceVariation<
  "contentWidthText",
  Simplify<TextSliceContentWidthTextPrimary>,
  never
>;

/**
 * Primary content in *Text → Quote → Primary*
 */
export interface TextSliceQuotePrimary {
  /**
   * Text field in *Text → Quote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.quote.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Background color field in *Text → Quote → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: text.quote.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_colour: prismic.ColorField;

  /**
   * Background image field in *Text → Quote → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text.quote.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Alignment field in *Text → Quote → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: text.quote.primary.alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  alignment: prismic.SelectField<"Left" | "Center" | "Right", "filled">;

  /**
   * Bottom margin field in *Text → Quote → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: text.quote.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Quote variation for Text Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceQuote = prismic.SharedSliceVariation<
  "quote",
  Simplify<TextSliceQuotePrimary>,
  never
>;

/**
 * Primary content in *Text → Wide text → Primary*
 */
export interface TextSliceWideTextPrimary {
  /**
   * Text field in *Text → Wide text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.wideText.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Alignment field in *Text → Wide text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: text.wideText.primary.alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  alignment: prismic.SelectField<"Left" | "Center" | "Right", "filled">;

  /**
   * Bottom margin field in *Text → Wide text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: text.wideText.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Wide text variation for Text Slice
 *
 * - **API ID**: `wideText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceWideText = prismic.SharedSliceVariation<
  "wideText",
  Simplify<TextSliceWideTextPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation =
  | TextSliceDefault
  | TextSliceContentWidthText
  | TextSliceQuote
  | TextSliceWideText;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Primary content in *TwoColumns → Default → Primary*
 */
export interface TwoColumnsSliceDefaultPrimary {
  /**
   * Left content field in *TwoColumns → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.default.primary.left_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  left_content: prismic.RichTextField;

  /**
   * Left image field in *TwoColumns → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.default.primary.left_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  left_image: prismic.ImageField<never>;

  /**
   * Right content field in *TwoColumns → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.default.primary.right_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  right_content: prismic.RichTextField;

  /**
   * Right image field in *TwoColumns → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.default.primary.right_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  right_image: prismic.ImageField<never>;

  /**
   * Background color field in *TwoColumns → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;

  /**
   * Background image field in *TwoColumns → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Bottom margin field in *TwoColumns → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: two_columns.default.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Default variation for TwoColumns Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColumnsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TwoColumnsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TwoColumns*
 */
type TwoColumnsSliceVariation = TwoColumnsSliceDefault;

/**
 * TwoColumns Shared Slice
 *
 * - **API ID**: `two_columns`
 * - **Description**: TwoColumns
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColumnsSlice = prismic.SharedSlice<
  "two_columns",
  TwoColumnsSliceVariation
>;

/**
 * Primary content in *Video → Full width video → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * Text above video field in *Video → Full width video → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Video from Media Library field in *Video → Full width video → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Select a video from Prismic media library
   * - **API ID Path**: video.default.primary.video_file
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video_file: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Video Embed (YouTube, Vimeo, etc.) field in *Video → Full width video → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: Paste a YouTube, Vimeo, or other video URL
   * - **API ID Path**: video.default.primary.video_embed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video_embed: prismic.EmbedField;

  /**
   * Background Colour field in *Video → Full width video → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_colour: prismic.ColorField;

  /**
   * Top Padding field in *Video → Full width video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.default.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Bottom Padding field in *Video → Full width video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.default.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Top margin field in *Video → Full width video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.default.primary.top_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Bottom margin field in *Video → Full width video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.default.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Full width video variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Video → Content width video → Primary*
 */
export interface VideoSliceContentWidthVideoPrimary {
  /**
   * Text above video field in *Video → Content width video → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.contentWidthVideo.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Video from Media Library field in *Video → Content width video → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Select a video from Prismic media library
   * - **API ID Path**: video.contentWidthVideo.primary.video_file
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video_file: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Video Embed (YouTube, Vimeo, etc.) field in *Video → Content width video → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: Paste a YouTube, Vimeo, or other video URL
   * - **API ID Path**: video.contentWidthVideo.primary.video_embed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video_embed: prismic.EmbedField;

  /**
   * Background Colour field in *Video → Content width video → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: video.contentWidthVideo.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_colour: prismic.ColorField;

  /**
   * Top margin field in *Video → Content width video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.contentWidthVideo.primary.top_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Top Padding field in *Video → Content width video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.contentWidthVideo.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Bottom Padding field in *Video → Content width video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.contentWidthVideo.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Bottom margin field in *Video → Content width video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.contentWidthVideo.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Content width video variation for Video Slice
 *
 * - **API ID**: `contentWidthVideo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceContentWidthVideo = prismic.SharedSliceVariation<
  "contentWidthVideo",
  Simplify<VideoSliceContentWidthVideoPrimary>,
  never
>;

/**
 * Primary content in *Video → Wide video → Primary*
 */
export interface VideoSliceWideVideoPrimary {
  /**
   * Text above video field in *Video → Wide video → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.wideVideo.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Video from Media Library field in *Video → Wide video → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Select a video from Prismic media library
   * - **API ID Path**: video.wideVideo.primary.video_file
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video_file: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Video Embed (YouTube, Vimeo, etc.) field in *Video → Wide video → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: Paste a YouTube, Vimeo, or other video URL
   * - **API ID Path**: video.wideVideo.primary.video_embed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video_embed: prismic.EmbedField;

  /**
   * Background Colour field in *Video → Wide video → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: video.wideVideo.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_colour: prismic.ColorField;

  /**
   * Top margin field in *Video → Wide video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.wideVideo.primary.top_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Top Padding field in *Video → Wide video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.wideVideo.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Bottom Padding field in *Video → Wide video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.wideVideo.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Bottom margin field in *Video → Wide video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.wideVideo.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Wide video variation for Video Slice
 *
 * - **API ID**: `wideVideo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceWideVideo = prismic.SharedSliceVariation<
  "wideVideo",
  Simplify<VideoSliceWideVideoPrimary>,
  never
>;

/**
 * Primary content in *Video → Browser width video → Primary*
 */
export interface VideoSliceBrowserWidthVideoPrimary {
  /**
   * Text above video field in *Video → Browser width video → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.browserWidthVideo.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Video from Media Library field in *Video → Browser width video → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Select a video from Prismic media library
   * - **API ID Path**: video.browserWidthVideo.primary.video_file
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video_file: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Video Embed (YouTube, Vimeo, etc.) field in *Video → Browser width video → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: Paste a YouTube, Vimeo, or other video URL
   * - **API ID Path**: video.browserWidthVideo.primary.video_embed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video_embed: prismic.EmbedField;

  /**
   * Background Colour field in *Video → Browser width video → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: video.browserWidthVideo.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_colour: prismic.ColorField;

  /**
   * Top margin field in *Video → Browser width video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.browserWidthVideo.primary.top_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Top Padding field in *Video → Browser width video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.browserWidthVideo.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Bottom Padding field in *Video → Browser width video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.browserWidthVideo.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;

  /**
   * Bottom margin field in *Video → Browser width video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video.browserWidthVideo.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_margin: prismic.SelectField<
    "None" | "Small" | "Medium" | "Large",
    "filled"
  >;
}

/**
 * Browser width video variation for Video Slice
 *
 * - **API ID**: `browserWidthVideo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceBrowserWidthVideo = prismic.SharedSliceVariation<
  "browserWidthVideo",
  Simplify<VideoSliceBrowserWidthVideoPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation =
  | VideoSliceDefault
  | VideoSliceContentWidthVideo
  | VideoSliceWideVideo
  | VideoSliceBrowserWidthVideo;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DiscountCodesDocument,
      DiscountCodesDocumentData,
      DiscountCodesDocumentDataCodeItem,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataColumnItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PostDocument,
      PostDocumentData,
      PostDocumentDataTypesItem,
      PostDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataVariationsItem,
      ProductDocumentDataLinkedProductsItem,
      ProductDocumentDataSlicesSlice,
      ProductDocumentDataGalleryItem,
      ProductCategoryDocument,
      ProductCategoryDocumentData,
      ProductCategoryDocumentDataSlicesSlice,
      AllDocumentTypes,
      BasketSlice,
      BasketSliceDefaultPrimary,
      BasketSliceVariation,
      BasketSliceDefault,
      BlogPostsSlice,
      BlogPostsSliceDefaultPrimary,
      BlogPostsSliceVariation,
      BlogPostsSliceDefault,
      CarouselSlice,
      CarouselSliceDefaultPrimarySlideItem,
      CarouselSliceDefaultPrimary,
      CarouselSliceVariation,
      CarouselSliceDefault,
      CheckoutFormSlice,
      CheckoutFormSliceDefaultPrimary,
      CheckoutFormSliceVariation,
      CheckoutFormSliceDefault,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceDefaultItem,
      FaqSliceVariation,
      FaqSliceDefault,
      GallerySlice,
      GallerySliceDefaultPrimary,
      GallerySliceDefaultItem,
      GallerySliceVariation,
      GallerySliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceContentWidthImagePrimary,
      ImageSliceWideImagePrimary,
      ImageSliceBrowserWidthImagePrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageSliceContentWidthImage,
      ImageSliceWideImage,
      ImageSliceBrowserWidthImage,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceContentWidthTextPrimary,
      TextSliceQuotePrimary,
      TextSliceWideTextPrimary,
      TextSliceVariation,
      TextSliceDefault,
      TextSliceContentWidthText,
      TextSliceQuote,
      TextSliceWideText,
      TwoColumnsSlice,
      TwoColumnsSliceDefaultPrimary,
      TwoColumnsSliceVariation,
      TwoColumnsSliceDefault,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceContentWidthVideoPrimary,
      VideoSliceWideVideoPrimary,
      VideoSliceBrowserWidthVideoPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
      VideoSliceContentWidthVideo,
      VideoSliceWideVideo,
      VideoSliceBrowserWidthVideo,
    };
  }
}
