// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  basket: dynamic(() => import("./Basket")),
  blog_posts: dynamic(() => import("./BlogPosts")),
  carousel: dynamic(() => import("./Carousel")),
  checkout_form: dynamic(() => import("./CheckoutForm")),
  contact_form: dynamic(() => import("./ContactForm")),
  faq: dynamic(() => import("./Faq")),
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  text: dynamic(() => import("./Text")),
  two_columns: dynamic(() => import("./TwoColumns")),
  video: dynamic(() => import("./Video")),
};
